<?php
/**
 * CandlestickTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CandlestickTest Class Doc Comment
 *
 * @category    Class
 * @description Candlestick
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CandlestickTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Candlestick"
     */
    public function testCandlestick()
    {
    }

    /**
     * Test attribute "close"
     */
    public function testPropertyClose()
    {
    }

    /**
     * Test attribute "close_time"
     */
    public function testPropertyCloseTime()
    {
    }

    /**
     * Test attribute "high"
     */
    public function testPropertyHigh()
    {
    }

    /**
     * Test attribute "low"
     */
    public function testPropertyLow()
    {
    }

    /**
     * Test attribute "number_of_trades"
     */
    public function testPropertyNumberOfTrades()
    {
    }

    /**
     * Test attribute "open"
     */
    public function testPropertyOpen()
    {
    }

    /**
     * Test attribute "open_time"
     */
    public function testPropertyOpenTime()
    {
    }

    /**
     * Test attribute "quote_asset_volume"
     */
    public function testPropertyQuoteAssetVolume()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }
}
