<?php
/**
 * FeeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FeeTest Class Doc Comment
 *
 * @category    Class
 * @description Fee
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FeeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Fee"
     */
    public function testFee()
    {
    }

    /**
     * Test attribute "msg_type"
     */
    public function testPropertyMsgType()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "fee_for"
     */
    public function testPropertyFeeFor()
    {
    }

    /**
     * Test attribute "multi_transfer_fee"
     */
    public function testPropertyMultiTransferFee()
    {
    }

    /**
     * Test attribute "lower_limit_as_multi"
     */
    public function testPropertyLowerLimitAsMulti()
    {
    }

    /**
     * Test attribute "fixed_fee_params"
     */
    public function testPropertyFixedFeeParams()
    {
    }

    /**
     * Test attribute "dex_fee_fields"
     */
    public function testPropertyDexFeeFields()
    {
    }
}
