<?php
/**
 * SyncInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SyncInfoTest Class Doc Comment
 *
 * @category    Class
 * @description SyncInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SyncInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SyncInfo"
     */
    public function testSyncInfo()
    {
    }

    /**
     * Test attribute "latest_block_hash"
     */
    public function testPropertyLatestBlockHash()
    {
    }

    /**
     * Test attribute "latest_app_hash"
     */
    public function testPropertyLatestAppHash()
    {
    }

    /**
     * Test attribute "latest_block_height"
     */
    public function testPropertyLatestBlockHeight()
    {
    }

    /**
     * Test attribute "latest_block_time"
     */
    public function testPropertyLatestBlockTime()
    {
    }

    /**
     * Test attribute "catching_up"
     */
    public function testPropertyCatchingUp()
    {
    }
}
