<?php
/**
 * TickerStatisticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TickerStatisticsTest Class Doc Comment
 *
 * @category    Class
 * @description TickerStatistics
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TickerStatisticsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TickerStatistics"
     */
    public function testTickerStatistics()
    {
    }

    /**
     * Test attribute "ask_price"
     */
    public function testPropertyAskPrice()
    {
    }

    /**
     * Test attribute "ask_quantity"
     */
    public function testPropertyAskQuantity()
    {
    }

    /**
     * Test attribute "bid_price"
     */
    public function testPropertyBidPrice()
    {
    }

    /**
     * Test attribute "bid_quantity"
     */
    public function testPropertyBidQuantity()
    {
    }

    /**
     * Test attribute "close_time"
     */
    public function testPropertyCloseTime()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "first_id"
     */
    public function testPropertyFirstId()
    {
    }

    /**
     * Test attribute "high_price"
     */
    public function testPropertyHighPrice()
    {
    }

    /**
     * Test attribute "last_id"
     */
    public function testPropertyLastId()
    {
    }

    /**
     * Test attribute "last_price"
     */
    public function testPropertyLastPrice()
    {
    }

    /**
     * Test attribute "last_quantity"
     */
    public function testPropertyLastQuantity()
    {
    }

    /**
     * Test attribute "low_price"
     */
    public function testPropertyLowPrice()
    {
    }

    /**
     * Test attribute "open_price"
     */
    public function testPropertyOpenPrice()
    {
    }

    /**
     * Test attribute "open_time"
     */
    public function testPropertyOpenTime()
    {
    }

    /**
     * Test attribute "prev_close_price"
     */
    public function testPropertyPrevClosePrice()
    {
    }

    /**
     * Test attribute "price_change"
     */
    public function testPropertyPriceChange()
    {
    }

    /**
     * Test attribute "price_change_percent"
     */
    public function testPropertyPriceChangePercent()
    {
    }

    /**
     * Test attribute "quote_volume"
     */
    public function testPropertyQuoteVolume()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "weighted_avg_price"
     */
    public function testPropertyWeightedAvgPrice()
    {
    }
}
