<?php
/**
 * TxTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TxTest Class Doc Comment
 *
 * @category    Class
 * @description Tx
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TxTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Tx"
     */
    public function testTx()
    {
    }

    /**
     * Test attribute "block_height"
     */
    public function testPropertyBlockHeight()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "confirm_blocks"
     */
    public function testPropertyConfirmBlocks()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "from_addr"
     */
    public function testPropertyFromAddr()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "time_stamp"
     */
    public function testPropertyTimeStamp()
    {
    }

    /**
     * Test attribute "to_addr"
     */
    public function testPropertyToAddr()
    {
    }

    /**
     * Test attribute "tx_age"
     */
    public function testPropertyTxAge()
    {
    }

    /**
     * Test attribute "tx_asset"
     */
    public function testPropertyTxAsset()
    {
    }

    /**
     * Test attribute "tx_fee"
     */
    public function testPropertyTxFee()
    {
    }

    /**
     * Test attribute "tx_hash"
     */
    public function testPropertyTxHash()
    {
    }

    /**
     * Test attribute "tx_type"
     */
    public function testPropertyTxType()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
    }

    /**
     * Test attribute "swap_id"
     */
    public function testPropertySwapId()
    {
    }

    /**
     * Test attribute "proposal_id"
     */
    public function testPropertyProposalId()
    {
    }
}
