<?php
/**
 * NodeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HTTP API
 *
 * The Binance Chain HTTP API provides access to a Binance Chain node deployment and market data services.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * NodeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NodeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for broadcastTx
     *
     * Broadcast a transaction..
     *
     */
    public function testBroadcastTx()
    {
    }

    /**
     * Test case for getAccount
     *
     * Get an account..
     *
     */
    public function testGetAccount()
    {
    }

    /**
     * Test case for getAccountSequence
     *
     * Get an account sequence..
     *
     */
    public function testGetAccountSequence()
    {
    }

    /**
     * Test case for getNodeInfo
     *
     * Get node information..
     *
     */
    public function testGetNodeInfo()
    {
    }

    /**
     * Test case for getPeers
     *
     * Get network peers..
     *
     */
    public function testGetPeers()
    {
    }

    /**
     * Test case for getTimeLocks
     *
     * Gets time lock records given an address.
     *
     */
    public function testGetTimeLocks()
    {
    }

    /**
     * Test case for getTransaction
     *
     * Get a transaction..
     *
     */
    public function testGetTransaction()
    {
    }

    /**
     * Test case for getValidators
     *
     * Get validators..
     *
     */
    public function testGetValidators()
    {
    }
}
